### ISSUE TITLE
Python.omn not installing

### ISSUE THREAD

**Issue by Terranigmus** [GeosoftInc/gxpy#113]
Downloading the "python_desktop_setup.gx " and executing it in the latest Geosoft 9.5 release shows up the message but does not install any files. 
Manually downloading the Python,omn file and putting it in "usr/omn" is of no use as the item does not show up in the menu manager.

**Comment by GeoTPop** [comment]
I had a similar problem using Geosoft 9.5 and the latest Anaconda distribution (3.7.1).  I was able to get it working by creating a 3.6 environment and configuring Oasis montaj to use that.

**Comment by hadiloosaeed** [comment]
You need to run python_desktop_setup.gx  from geosoft Run GX. 

you can download python_desktop_setup.gx  from this site.
https://github.com/GeosoftInc/gxpy/wiki/Python-menu-for-Geosoft-Desktop
