### ISSUE TITLE
Some tutorial images are located on internal Geosoft server, which isn't accessible to all users

### ISSUE THREAD

**Issue by GeoTPop** [GeosoftInc/gxpy#114]
Viewing the PyCharm IDE page (https://geosoftgxdev.atlassian.net/wiki/spaces/GXD93/pages/102957212/PyCharm+IDE), images are located on the internal Confluence site and aren't available unless I am connected to the Geosoft VPN.
e.g. http://confluence.geosoft.com/download/attachments/35850441/image2017-6-8_10-16-55.png?version=1&modificationDate=1496931414623&api=v2

**Comment by serban-seeq** [comment]
cannot reproduce
