### ISSUE TITLE
when I run hello world from configure python I get error?

### ISSUE THREAD

**Issue by hadiloosaeed** [GeosoftInc/gxpy#115]
After running hello world from configure python geosoft shows just "hello" but after that gave some errors . this is first error that shows:
" Unable to locate the ?!GetLicencedUser_SYS@@YAJPEAVH_GXX@@PEADPEBJ12@Z function in the geoengine.cor dynamic object.
How can I correct this problem and and create GX with python.

**Comment by serban-seeq** [comment]
You will need to login to seequent connector first.
