### ISSUE TITLE
Incompatible with numpy==1.16

### ISSUE THREAD

**Issue by orerocks** [GeosoftInc/gxpy#116]
A change in numpy security in 1.16 causes gxpy to crash when reading any grid or database:
```
~\AppData\Local\Continuum\anaconda3\lib\site-packages\geosoft\gxpy\vv.py in _get_data_np(self, start, n, dtype)
    249         self.gxvv.get_data(start, n, bytearr, gxu.gx_dtype_dimension(dtype, self._dim))
    250         npd = np.frombuffer(bytearr, dtype=dtype).reshape(sh)
--> 251         npd.flags['WRITEABLE'] = True
    252         return npd
    253 

ValueError: cannot set WRITEABLE flag to True of this array
```
(example from [Geosoft Grid Tutorial](https://github.com/GeosoftInc/gxpy/blob/master/examples/jupyter_notebooks/Tutorials/Grids%20and%20Images.ipynb))

This affected other packages like [PyTables](https://github.com/PyTables/PyTables/issues/719) too, but they have implemented fixes.

Rolling back to numpy==1.15.4 works, but is difficult to sustain.

**Comment by jbgeosoft** [comment]
This should now be fixed in master branch. We have not released the 9.6 updates on Github yet and still have one other internal issue to clear up with the distribution. I will include this fix in the 9.6 update.
