### ISSUE TITLE
Ability to use gxpy on a headless system without logging in

### ISSUE THREAD

**Issue by robintw** [GeosoftInc/gxpy#122]
We're keen to use gxpy on some cloud-based systems to convert files from Geosoft format to other formats. However, it seems that when you use gxpy it will pop up a dialog asking you to login to Sequent Connector - which requires user interaction. We'd like to be able to do these format conversions automatically, without having someone click buttons to login each time.

Is there a way to configure the login system to automatically use a specific username and password, rather than popping up a dialog box asking you to login?

Alternatively, are there any other ways to use gxpy without user interaction?

**Comment by serban-seeq** [comment]
Once logged into Seequent connector, the machine should stay logged in a number of days. Occasionally you will need to log back in. Seequent Connector does not have a headless login mode.
