### ISSUE TITLE
gxgrd.Grid.minimum_curvature(xyv) doesn't work for large datasets

### ISSUE THREAD

**Issue by TheZappie** [GeosoftInc/gxpy#127]
```python
import numpy as np
from geosoft.gxpy import grid as gxgrd
from geosoft import gxpy

n = 15_000_000
xyv = np.random.rand(n, 3)
with gxpy.gx.GXpy(suppress_progress=True) as context:
    grid = gxgrd.Grid.minimum_curvature(xyv)
```

Error message:

`geosoft.gxapi.GXError: Unable to write data to the database because the data is too large for this database configuration. The maximum amount of data you can store in this database for a single line and channel is 64.00 meg. The current operation is attempting to write 104.01 meg of data. To change this limit you must create a new database that supports your data storage requirements. Run "Create new database" and select the advanced options where database limits can be specified.
`

Solution: allocate sufficient space to the database when it is created when calling gxgrd.Grid.minimum_curvature

**Comment by serban-seeq** [comment]
you can also use the `GXDB.Grow` method to resize a database after its been created, but be careful as this can wipe the data inside

https://geosoftinc.github.io/gxpy/2023.1/python/GXDB.html
