### ISSUE TITLE
project.py does not support Geosoft surface document type

### ISSUE THREAD

**Issue by tompopowski** [GeosoftInc/gxpy#133]
The document type "Geosurface" is missing from project.py:
`DOC_TYPE_DATABASE = "Database"`
`DOC_TYPE_GRID = "Grid"`
`DOC_TYPE_MAP = "Map"`
`DOC_TYPE_3DV = "3DView"`
`DOC_TYPE_VOXEL = "Voxel"`
`DOC_TYPE_VOXI = "VoxelInversion"`
`DOC_TYPE_GMS3D = "GMS3D"`
`DOC_TYPE_GMS2D = "GMS2D"`
`DOC_TYPE_ALL = "All"`

The underlying gxapi functions support it (see gxapi\gxproj.py).

**Comment by serban-seeq** [comment]
GXDEV-40

**Comment by serban-seeq** [comment]
Fixed in 2024.2
