### ISSUE TITLE
Unequal channel length within line within geodatabase

### ISSUE THREAD

**Issue by TheZappie** [GeosoftInc/gxpy#137]
I have an issue reading specific geodatabases, I have attached one in it this ticket. I have narrowed down the issue, discarded all irrelevant data from the geodatabase that aren't needed to reproduce the issue. [gdb-with_issue.zip](https://github.com/user-attachments/files/17013346/gdb-with_issue.zip)

When reading the database, the size of the channel is different depending on which channel is read. See the below code to reproduce the issue.

Key question: Should channels inside a line inside gdb always have the same length?

```python
from geosoft import gxpy

with gxpy.gx.GXpy(suppress_progress=True):
    with gxpy.gdb.Geosoft_gdb.open(r"C:\Users\v.savenije\Documents\geosoft projects\test.gdb") as gdb:
       if len(gdb.read_channel_vv('LN38K0931P1_P1', "MAG_RES")) != len(gdb.read_channel_vv('LN38K0931P1_P1', "Signal_Strength")):
            raise Exception("Channels do not have the same length")
```

**Comment by serban-seeq** [comment]
> Should channels inside a line inside gdb always have the same length?
There is no such requirement

[](https://help.seequent.com/Oasismontaj/2024.1/Content/ss/prepare_om/work_with_databases/c/oasis_databases.htm?tocpath=Concepts%7CGeosoft%20Databases%7C_____0)

**Comment by TheZappie** [comment]
Thanks for answering on this by the way, this question was rejected when asked on my.seequent.com/support .  Somehow I was always thought that gdb lines are tables, as in a rectangular data structure, but I should clearly non-equal fiducials should be accounted for.
