### ISSUE TITLE
Cython gxapi generation

### ISSUE THREAD

**Issue by ianneilmacleod** [GeosoftInc/gxpy#27]
@jbgeosoft

**Comment by jbgeosoft** [comment]
This has been completed. The following 2 scripts in  the gxapi branch is responsible for the API generation:

https://github.com/GeosoftInc/gxapi/blob/master/gen_cython.py
https://github.com/GeosoftInc/gxapi/blob/master/gen_python.py


The API spec files will from now on be used to maintain the API and documentation.
