### ISSUE TITLE
Invalid gxapi constant formating

### ISSUE THREAD

**Issue by ianneilmacleod** [GeosoftInc/gxpy#36]
gxapi.IMG_QUERY_rCOMPRESSION_RATIO should be gxapi.IMG_QUERY_COMPRESSION_RATIO.  Note the 'r' before COMPRESSION.  This is just one example of the problematic pattern in gxapi.

**Comment by ianneilmacleod** [comment]
I suggest that manifests should not change, or if we are compelled to change them then we should keep the old as deprecated.

**Comment by ianneilmacleod** [comment]
Note the odd old ones like iDUMMY and rDUMMY, which also need to stay.

**Comment by jbgeosoft** [comment]
Hi Ian, 

This did not change between 9.2.1 and 9.3., or am I misunderstanding? Here is 9.2.1, and I see the same for 9.3:

```
e:\ggit\t\kernel>e:\Anaconda3\Scripts\pip uninstall geosoft
Uninstalling geosoft-9.3.0:
  e:\anaconda3\lib\site-packages\geosoft.egg-link
Proceed (y/n)? y
  Successfully uninstalled geosoft-9.3.0

e:\ggit\t\kernel>e:\Anaconda3\Scripts\pip install geosoft
Collecting geosoft
  Using cached geosoft-9.2.1-cp36-none-win_amd64.whl
...
Installing collected packages: geosoft
Successfully installed geosoft-9.2.1

e:\ggit\t\kernel>python.exe
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import geosoft.gxa as gxa
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'geosoft.gxa'
>>> import geosoft.gxapi as gxa
>>> gxa.IMG_QUERY_rCOMPRESSION_RATIO
18
>>> gxa.IMG_QUERY_COMPRESSION_RATIO
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'geosoft.gxapi' has no attribute 'IMG_QUERY_COMPRESSION_RATIO'
>>>
>>> gxa.rDUMMY
-1e+32
```

**Comment by ianneilmacleod** [comment]
Maybe it is me. I had a tutorial that used this constant and it stopped working, but perhaps I had not tested it after replacing with the constant. I'll check again, closing for now.

**Comment by ianneilmacleod** [comment]
Verified - yes, I must have changed the code without testing.  Thanks @jbgeosoft .
