### ISSUE TITLE
Need a way to set "smooth" surface setting for a VOXD.

### ISSUE THREAD

**Issue by ianneilmacleod** [GeosoftInc/gxpy#58]

**Comment by ianneilmacleod** [comment]
Other settings that come to mind:
fill
wireframe
clip limits
depth mode (switch z orientation to present with depth, z positive down).
performance settings
anything else?

**Comment by charliecq** [comment]
I added render mode setter/getter for VOXD in master branch:
SetRenderMode_VOXD, GetRenderMode_VOXD

**Comment by ianneilmacleod** [comment]
@charliecq now that you have the SetRenderMode_VOXD, can you look at the other mode settings and use the pattern to set all that are reasonable?

**Comment by charliecq** [comment]
@ianneilmacleod sure, I'll take a look at other settings that are reasonable

**Comment by charliecq** [comment]
@ianneilmacleod After taking a look at the VOXD class, I found that all other available display-related settings are exported through SetDrawControls_VOXD/GetDrawControls_VOXD.

**Comment by ianneilmacleod** [comment]
@charlieqc Thanks for the GetDrawControls_VOXD.

I reopenned the related https://github.com/GeosoftInc/gxapi/issues/12 as the existing test_vox_display test terminates.
