### ISSUE TITLE
Investigate why temporary files remain locked in some cases using 'with' pattern with exceptions

### ISSUE THREAD

**Issue by jacquesbeaurain** [GeosoftInc/gxpy#82]
We have the following pattern in gxpy in a number of places:

    if self._remove:
        try:
            delete_files(self._file_name)
        except OSError:
            pass

It can be reproduced by using with statement with some exception. E.g. in test_grid.test_image_file without an d_imggxd.dll or one of its dependencies present. See related comments in gxmap.Map._close but probably occurs elsewhere.

**Comment by jbgeosoft** [comment]
This issue can leads to multiple confusing exceptions being thrown if not hidden like above.

**Comment by ianneilmacleod** [comment]
@jbgeosoft - was this resolved?  If not, happy to look at it if you can narrow the use-case.
