### ISSUE TITLE
Why geosoft.gxpy not working?

### ISSUE THREAD

**Issue by aguany** [GeosoftInc/gxpy#92]
Very new to Geosoft. Installed gxpy module and obtained a Geosoft ID. How can I test run a Geosoft jupyter notebook Tutorials, e.g., the "Coordinate Systems.ipynb"? It does not do anything now. Do I need to call a function with my Geosoft ID first?

**Comment by ianneilmacleod** [comment]
Sorry @aguany , just seeing this now.  I suggest you start with the tutorial: https://geosoftgxdev.atlassian.net/wiki/spaces/GXD93/pages/103153671/Python+Tutorial+for+Geosoft+GX+Developer

Also, better to use the GX Developer forum in MyGeosoft for help like this as it has a better chance of being more responsive:
https://my.geosoft.com/forum

**Comment by aguany** [comment]
Thanks, Ian. I have raised the question on my.geosoft.com/forum.

Allen

**Comment by aguany** [comment]
Well, I saw the question posted, but now I can’t see it.

Allen

From: Guan, Allen
Sent: Monday, April 30, 2018 8:27 AM
To: 'GeosoftInc/gxpy' <reply@reply.github.com>; GeosoftInc/gxpy <gxpy@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [GeosoftInc/gxpy] Why geosoft.gxpy not working? (#92)

Thanks, Ian. I have raised the question on my.geosoft.com/forum.

Allen

**Comment by ianneilmacleod** [comment]
@aguany just reviewing stale open issues.  Did you get past your early challenges?
